Demo3/Models/Shop.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

Demo3/Controllers/LoginUserController.cs
using Demo3.Controllers;
using Demo3.Models;
using System;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using System.Web.Security;


public class LoginUserController : Controller
{
    ShopCartEntities db = new ShopCartEntities(); // Sử dụng context của bạn

    public ActionResult Login()
    {
        return View();
    }

    [HttpPost]
    [ValidateAntiForgeryToken]
    public ActionResult Login(LoginViewModel model)
    {
        if (ModelState.IsValid)
        {
            var user = db.Users.FirstOrDefault(u => u.Email == model.Email && u.Password == model.Password);
            if (user != null)
            {
                FormsAuthentication.SetAuthCookie(model.Email, false);
                FormsAuthentication.SetAuthCookie(model.UserName, false);
                // Lưu thông tin người dùng vào session hoặc cookie nếu cần
                Session["UserId"] = user.IDus;
                Session["UserName"] = user.UserName;
                return RedirectToAction("Index", "Home"); // Chuyển hướng sau khi đăng nhập thành công
            }
            else
            {
                ModelState.AddModelError("", "Invalid email or password.");
            }
        }
        return View(model);
    }

    public ActionResult Logout()
    {
        FormsAuthentication.SignOut();
        // Xóa thông tin người dùng khỏi session hoặc cookie nếu cần
        Session.Remove("UserId");
        Session.Remove("UserName");
        return RedirectToAction("Index", "Home"); // Chuyển hướng sau khi đăng xuất
    }

}

Demo3/Controllers/ProductController.cs
using Demo3.Models;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace Demo3.Controllers
{
    public class ProductController : Controller
    {
        ShopCartEntities db = new ShopCartEntities();
        // GET: Product
        public ActionResult SearchOption(double min = double.MinValue, double max = double.MaxValue)
        {
            var list = db.Products.Where(p => (double)p.Price >= min && (double)p.Price <= max).ToList();
            return View(list);
        }
        public ActionResult Index(string category)
        {
            if (category == null)
            {
                var productList = db.Products.OrderByDescending(x => x.Name);
                return View(productList);
            }
            else
            {
                var productList = db.Products.OrderByDescending(x => x.Name).Where(x => x.Category == category);
                return View(productList);

            }
        }
        public ActionResult Create()
        {
            Product pro = new Product();
            return View(pro);
        }
        public ActionResult SelectCate()
        {
            Category se_cate = new Category
            {
                ListCate = db.Categories.ToList<Category>()
            };
            return PartialView(se_cate);
        }
        [HttpPost]
        public ActionResult Create(Product pro)
        {
            try
            {
                if (pro.UploadImage != null)
                {
                    string filename = Path.GetFileNameWithoutExtension(pro.UploadImage.FileName);
                    string extent = Path.GetExtension(pro.UploadImage.FileName);
                    filename = filename + extent;
                    pro.ImagePro = "~/Content/sources/images/" + filename;
                    pro.UploadImage.SaveAs(Path.Combine(Server.MapPath("~/Content/sources/images/"), filename));
                }
                db.Products.Add(pro);
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            catch
            {
                return View();
            }

        }
        public ActionResult Delete(int id)
{
    // Tìm sản phẩm cần xóa dựa trên ID
        var productToDelete = db.Products.Find(id);

    if (productToDelete == null)
    {
        // Nếu không tìm thấy sản phẩm, bạn có thể xử lý lỗi hoặc chuyển hướng đến trang 404 Not Found.
        return HttpNotFound();
    }

    // Xóa sản phẩm khỏi cơ sở dữ liệu
    db.Products.Remove(productToDelete);
    db.SaveChanges();

    // Chuyển hướng đến trang Index sau khi xóa sản phẩm thành công
    return RedirectToAction("Index");
}

    }
}

Demo3/Views/Shared/About.cshtml
<!DOCTYPE html>

<html lang="en">

<head>

    <meta charset="UTF-8">

    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    <title>Document</title>

    <link rel="stylesheet" href="~/Content/sources/style.css">

    <link rel="icon" type="image/x-icon" href="../Content/sources/images/k-high-resolution-logo-white.png">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />

    <style>
        h2 {
            color: #000000;
        }

        p {
            color: #000000;
        }

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        header {
            background-color: #333;
            color: #fff;
            padding: 10px 0;
            text-align: center;
        }

        .container {
            max-width: 1000px;
            margin: 0 auto;
            padding: 20px;
        }

        .about-image {
            width: auto;
            height: auto;
            margin-right: 50px;
        }

        .about-flex {
            display: flex;
            margin-bottom: 50px;
        }

        .about-text {
            width: 50%;
            border: 3px;
            padding: 10px;
            margin: auto;
        }
    </style>

</head>

<body>

   <section id="header">
    <a href="#"><img src="../Content/sources/images/logo-black.png" class="logo" alt=""></a>
    <div>
        <ul id="navbar">
            <li><a href="@Url.Action("Index", "Home")">Home</a></li>
            <li><a href="@Url.Action("ShopView", "Home")">Shop</a></li>
            <li><a href="@Url.Action("AboutView", "Home")">About</a></li>
            <li><a href="@Url.Action("ContactView", "Home")">Contact</a></li>
            <li><a href="search.html"><i class="fas fa-search"></i> </a></li>
            <li><a href="@Url.Action("Login", "LoginUser")"><i class="fas fa-user"></i></a></li>
            <li><a href="cart.html"><i class="fas fa-shopping-cart" style="color: #000000;"></i></a></li>
            <li class="format-hello">
                @if (Session["UserName"] == null)
                {
                    <span>Hello</span>
                }
                else
                {
                    <span><text>Hello  </text>@Session["UserName"]</span>
                }
            </li>
            <li><a href="@Url.Action("Logout", "LoginUser")"><i class="fas fa-sign-out-alt"></i></a></li>
            
        </ul>
    </div>
</section>

    <div class="container">

        <div>

            <div class="about-flex">

                <img class="about-image" src="https://images.unsplash.com/photo-1698819718444-0d59d1011410?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDEyfFM0TUtMQXNCQjc0fHxlbnwwfHx8fHw%3D" alt="About Us Image">

                <div class="about-text">

                    <h2>WHO WE ARE?</h2>

                    <p>
                        KARA we are passionate about providing our customers with the latest and trendiest fashion

                        pieces. Our team of dedicated fashion enthusiasts carefully curates our collection to offer you the best

                        in style and quality.
                    </p>

                </div>

            </div>

            <div class="about-flex">

                <img class="about-image" src="https://images.unsplash.com/photo-1697659984086-805972afd080?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDc5fFM0TUtMQXNCQjc0fHxlbnwwfHx8fHw%3D" alt="About Us Image">

                <div class="about-text">

                    <h2>Our Mission</h2>

                    <p>
                        Our mission is to empower individuals to express their unique style through fashion. We believe that

                        clothing is not just a way to cover the body, but a form of self-expression and confidence. We strive to

                        inspire and enable everyone to embrace their individuality and showcase their personality through the

                        clothes they wear.
                    </p>

                </div>

            </div>

            <div class="about-flex">

                <img class="about-image" src="https://images.unsplash.com/photo-1698790706733-75ed1a8fd60c?auto=format&fit=crop&q=60&w=500&ixlib=rb-4.0.3&ixid=M3wxMjA3fDB8MHx0b3BpYy1mZWVkfDF8UzRNS0xBc0JCNzR8fGVufDB8fHx8fA%3D%3D" alt="About Us Image">

                <div class="about-text">

                    <h2>Why Choose Us?</h2>

                    <p>

                        <li>Wide selection of trendy and high-quality clothing items</li>

                        <li>Excellent customer service and support</li>

                        <li>Fast and reliable worldwide shipping</li>

                        <li>Regularly updated collections to keep you in style</li>

                        <li>100% satisfaction guarantee</li>

                    <p>

                </div>

            </div>

        </div>

    </div>

    <footer class="section-p1">

        <div class="col">

            <img class="logo" src="/../Content/sources/images/logo-black.png" width="100" height="100" alt="">

            <h7>Contact</h7>

            <p3>
                <strong>Address: </strong>2443 Sierra Nevada Road, Mammoth Lakes CA 93546

            </p3>

            <p3>
                <strong>Phone:</strong> kara:0704856946 genti:0967285710

            </p3>

            <p3><strong>Hours: </strong>10:00 - 18:00.Mon-Sat</p3>

            <div class="follow">

                <h7>follow us</h7>

                <div class="icon">

                    <i class="fab fa-facebook"></i>

                    <i class="fab fa-instagram"></i>

                    <i class="fab fa-youtube"></i>

                </div>

            </div>

        </div>

        <div class="col">

            <h7>About</h7>

            <a href="#">About Us</a>

            <a href="#">Delivery Information</a>

            <a href="#">Privacy policy</a>

            <a href="#">Terms & Conditions</a>

            <a href="#">Contact Us</a>

        </div>

        <div class="col">

            <h7>My Account</h7>

            <a href="#">Sign In</a>

            <a href="#">View Cart</a>

            <a href="#">My Wishlist</a>

            <a href="#">Track My Order</a>

            <a href="#">Help</a>

        </div>

        <div class="col-install">

            <p3>Install App</p3>

            <p3>From App Store or Google Play</p3>

            <div class="row">

                <img src="../Content/sources/dowload/App_Store_(iOS)-Badge-Alternative-Logo.wine.png" width="200" height="150">

                <img src="../Content/sources/dowload/Google_Play-Badge-Logo.wine.png" width="200" height="150">

            </div>

            <p3> Secured Payment Gateways </p3>

            <img src="../Content/sources/dowload/small.jpg">

        </div>

        <div class="copyright">

            <p3> 2023, AE206 etc - HTML CSS Ecommerce Template</p3>

        </div>
        @RenderBody()
    </footer>

</body>

</html>

Demo3/Views/Shared/Contact.cshtml
<!DOCTYPE html>

<html>

<head>

    <meta charset="UTF-8">

    <title>Kara</title>

    <meta name="viewport" content="width=device-width">

    <link rel="stylesheet" href="~/Content/sources/style.css">

    <link rel="icon" type="image/x-icon" href="~/Content/sources/images/k-high-resolution-logo-white.png">

    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />

    <style>

        body {
            font-family: Arial, sans-serif;
            margin: 0;
            padding: 0;
            background-color: #f4f4f4;
        }

        .container {
            width: 80%;
            margin: auto;
            overflow: hidden;
        }

        .contact-info {
            background: #f9f9f9;
            padding: 20px;
            margin-top: 50px;
            border-radius: 10px;
        }

            .contact-info h2 {
                margin-bottom: 20px;
            }

        .contact-details {
            margin-bottom: 10px;
        }

        #contact-form {
            background: #f9f9f9;
            padding: 20px;
            margin-top: 50px;
            border-radius: 10px;
        }

        .form-group {
            margin-bottom: 15px;
        }

            .form-group input[type="text"],
            .form-group input[type="email"] {
                width: 100%;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .form-group textarea {
                width: 100%;
                padding: 10px;
                margin-bottom: 10px;
                border: 1px solid #ccc;
                border-radius: 5px;
            }

            .form-group button[type="submit"] {
                background: #333;
                color: #fff;
                border: none;
                padding: 10px 20px;
                border-radius: 5px;
                cursor: pointer;
            }
    </style>

</head>

<body>

    <section id="header">
        <a href="#"><img src="../Content/sources/images/logo-black.png" class="logo" alt=""></a>
        <div>
            <ul id="navbar">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="@Url.Action("ShopView", "Home")">Shop</a></li>
                <li><a href="@Url.Action("AboutView", "Home")">About</a></li>
                <li><a href="@Url.Action("ContactView", "Home")">Contact</a></li>
                <li><a href="search.html"><i class="fas fa-search"></i> </a></li>
                <li><a href="@Url.Action("Login", "LoginUser")"><i class="fas fa-user"></i></a></li>
                <li><a href="cart.html"><i class="fas fa-shopping-cart" style="color: #000000;"></i></a></li>
                <li class="format-hello">
                    @if (Session["UserName"] == null)
                    {
                        <span>Hello</span>
                    }
                    else
                    {
                        <span><text>Hello  </text>@Session["UserName"]</span>
                    }
                </li>
                <li><a href="@Url.Action("Logout", "LoginUser")"><i class="fas fa-sign-out-alt"></i></a></li>

            </ul>
        </div>
    </section>

    <div class="container">

        <div class="contact-info">

            <h5>Contact Info</h5>

            <div class="contact-details">

                <strong>Address:</strong> 176 Cong Hoa street , ward 12 , Tân Bình district , Ho Chi Minh city

            </div>

            <div class="contact-details">

                <strong>Tel và Zalo:</strong> <a href="tel://0913885457">0913885457</a>

            </div>

            <div class="contact-details">

                <strong>Email:</strong> phucle9426@gmail.com

            </div>

            <div class="contact-details">

                <strong>Facebook:</strong> <a href="https://www.facebook.com/PhucLe2735"> Phuc Le</a>

            </div>

            <div class="contact-details">

                <strong>Instagram:</strong> <a href="https://www.instagram.com/_.phucle._/">_.phucle._</a>

            </div>

            <div class="contact-details">

                <strong>Work Time:</strong> Monday to Sunday: 9:00 AM - 6:00 PM

            </div>

        </div>

    </div>

    <div class="container">

        <div id="contact-form">

            <h5>Contact Us</h5>

            <form action="process_form.php" method="post">

                <div class="form-group">

                    <label for="name">Full Name:</label>

                    <input type="text" id="name" name="name" required>

                </div>

                <div class="form-group">

                    <label for="email">Email:</label>

                    <input type="email" id="email" name="email" required>

                </div>

                <div class="form-group">

                    <label for="message">Content:</label>

<textarea id="message" name="message" rows="5" required></textarea>

                </div>

                <div class="form-group">

                    <button type="submit">Send</button>

                </div>

            </form>

        </div>

        <footer class="section-p1">

            <div class="col">

                <h7>About</h7>

                <a href="#">About Us</a>

                <a href="#">Delivery Information</a>

                <a href="#">Privacy policy</a>

                <a href="#">Terms & Conditions</a>

                <a href="#">Contact Us</a>

            </div>

            <div class="col">

                <h7>My Account</h7>

                <a href="#">Sign In</a>

                <a href="#">View Cart</a>

                <a href="#">My Wishlist</a>

                <a href="#">Track My Order</a>

                <a href="#">Help</a>

            </div>

            <div class="col-install">

                <p3>Install App</p3>

                <p3>From App Store or Google Play</p3>

                <div class="row">

                    <img src="~/Content/sources/dowload/App_Store_(iOS)-Badge-Alternative-Logo.wine.png" width="200" height="150">

                    <img src="~/Content/sources/dowload/Google_Play-Badge-Logo.wine.png" width="200" height="150">

                </div>

                <p3> Secured Payment Gateways </p3>

                <img src="~/Content/sources/dowload/small.jpg">

            </div>

            <div class="copyright">

                <p3> 2023, AE206 etc - HTML CSS Ecommerce Template</p3>

            </div>
            @RenderBody()

        </footer>

</body>

</html>

Demo3/Views/Shared/_Layout2.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Kara</title>
    <meta name="viewport" content="width=device-width">
    <link rel="stylesheet" href="~/Content/sources/style.css">
    <link rel="icon" type="image/x-icon" href="/../Content/sources/images/k-high-resolution-logo-white.png">
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.15.4/css/all.css" />

</head>
<body>
    <section id="header">
        <a href="#"><img src="../Content/sources/images/logo-black.png" class="logo" alt=""></a>
        <div>
            <ul id="navbar">
                <li><a href="@Url.Action("Index", "Home")">Home</a></li>
                <li><a href="@Url.Action("ShopView", "Home")">Shop</a></li>
                <li><a href="@Url.Action("AboutView", "Home")">About</a></li>
                <li><a href="@Url.Action("ContactView", "Home")">Contact</a></li>
                <li><a href="search.html"><i class="fas fa-search"></i> </a></li>
                <li><a href="@Url.Action("Login", "LoginUser")"><i class="fas fa-user"></i></a></li>
                <li><a href=@Url.Action("Index", "Product")><i class="fas fa-shopping-cart" style="color: #000000;"></i></a></li>
                <li class="format-hello">
                    @if (Session["UserName"] == null)
                    {
                        <span>Hello</span>
                    }
                    else
                    {
                        <span><text>Hello  </text>@Session["UserName"]</span>
                    }
                </li>
                <li><a href="@Url.Action("Logout", "LoginUser")"><i class="fas fa-sign-out-alt"></i></a></li>
                
            </ul>
        </div>
    </section>
    <hr>


    <section id="cat">
        <h1>Trade-in-offer</h1>
        <h2>Super value deals</h2>
        <h3>On all products</h3>
        <p>Save more with coupons & up to 70% off!</p>
        <button>Shop Now</button>
    </section>



    <section id="features" class="section-p1">
        <div class="fe-box">
            <img src="/../Content/sources/Features/Mail sent-bro.png" width="150" height="150">
            <h4>Free Shipping</h4>

        </div>
        <div class="fe-box">
            <img src="/../Content/sources/Features/Fashion blogging-amico.png" width="150" height="150">
            <h4>Online Order</h4>

        </div>
        <div class="fe-box">
            <img src="/../Content/sources/Features/Retail markdown-pana.png" width="150" height="150">
            <h4>Sales</h4>

        </div>
        <div class="fe-box">
            <img src="/../Content/sources/Features/Money income-bro.png" width="150" height="150">
            <h4>Save Money</h4>

        </div>
        <div class="fe-box">
            <img src="/../Content/sources/Features/Active Support-bro.png" width="150" height="150">
            <h4>24/7 Support</h4>

        </div>
        <div class="fe-box">
            <img src="/../Content/sources/Features/Gift card-pana.png" width="150" height="150">
            <h4>Voucher</h4>

        </div>


    </section>



    <section id="products-f" class="section-p1">
        <h5>Features Products</h5>
        <p3> New Collection</p3>
        <div class="pro-container">

            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>

            <div class="pro">
                <img src="../Content/sources/Pro/aokhoac.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>
            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>

            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>

            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>

            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>

            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>

            <div class="pro">
                <img src="../Content/sources/Pro/370218590_887965675595704_646111386393386377_n.jpg">
                <div class="des">
                    <span>Kara</span>
                    <h5>Basic red t-shirt</h5>
                    <div class="star">
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                        <i class="fas fa-star"></i>
                    </div>
                    <h4>$24</h4>
                </div>
                <a href="#"><i class="fas fa-shopping-cart"></i></a>
            </div>
        </div>
    </section>

    <section id="banner" class="#e8f6ea">
        <h6>Repair Services</h6>
        <h5>Up to <span>70% Off</span>- All t-shirts && Accessories</h5>
        <button class="normal">Expolore More</button>
    </section>
    <footer class="section-p1">
        <div class="col">
            <img class="logo" src="/../Content/sources/images/logo-black.png" width="100" height="100" alt="">
            <h7>Contact</h7>
            <p3>
                <strong>Address: </strong>2443 Sierra Nevada Road, Mammoth Lakes CA 93546
            </p3>
            <p3>
                <strong>Phone:</strong> kara:0704856946 genti:0967285710
            </p3>
            <p3><strong>Hours: </strong>10:00 - 18:00.Mon-Sat</p3>
            <div class="follow">
                <h7>follow us</h7>
                <div class="icon">
                    <i class="fab fa-facebook"></i>
                    <i class="fab fa-instagram"></i>
                    <i class="fab fa-youtube"></i>
                </div>
            </div>
        </div>

        <div class="col">
            <h7>About</h7>
            <a href="#">About Us</a>
            <a href="#">Delivery Information</a>
            <a href="#">Privacy policy</a>
            <a href="#">Terms & Conditions</a>
            <a href="#">Contact Us</a>
        </div>
        <div class="col">
            <h7>My Account</h7>
            <a href="#">Sign In</a>
            <a href="#">View Cart</a>
            <a href="#">My Wishlist</a>
            <a href="#">Track My Order</a>
            <a href="#">Help</a>
        </div>
        <div class="col-install">
            <p3>Install App</p3>
            <p3>From App Store or Google Play</p3>
            <div class="row">
                <img src="/../Content/sources/dowload/App_Store_(iOS)-Badge-Alternative-Logo.wine.png" width="200" height="150">
                <img src="/../Content/sources/dowload/Google_Play-Badge-Logo.wine.png" width="200" height="150">
            </div>
            <p3> Secured Payment Gateways </p3>
            <img src="/../Content/sources/dowload/small.jpg">
            @RenderBody()
        </div>
        <div class="copyright">
            <p3><text>2023, AE206 etc - HTML CSS Ecommerce Template</text></p3>
        </div>

    </footer>
    <script src="~/Scripts/script .js"></script>
</body>
</html>